doctrine:
    dbal:
        driver: '%env(resolve:DATABASE_DRIVER)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        server_version: 5.7
        charset: UTF8
        schema_filter: ~^(?!fos_)~
        types:
            user_id: App\Infrastructure\User\Persistence\Doctrine\Type\UserIdType
            booking_id: App\Infrastructure\Booking\Persistence\Doctrine\Type\BookingIdType
            session_id: App\Infrastructure\Session\Persistence\Doctrine\Type\SessionIdType
            name: App\Infrastructure\Shared\Persistence\Doctrine\Type\NameType
            lastname: App\Infrastructure\Shared\Persistence\Doctrine\Type\LastNameType
            email: App\Infrastructure\Shared\Persistence\Doctrine\Type\EmailType
            creation_date: App\Infrastructure\Shared\Persistence\Doctrine\Type\CreationDateType
            updated_at: App\Infrastructure\Shared\Persistence\Doctrine\Type\UpdatedAtType
            when: App\Infrastructure\Shared\Persistence\Doctrine\Type\WhenType
            unsubscribed_at: App\Infrastructure\Booking\Persistence\Doctrine\Type\UnsubscribedAtType
            status: App\Infrastructure\Session\Persistence\Doctrine\Type\StatusType
            duration: App\Infrastructure\Session\Persistence\Doctrine\Type\DurationType
            max_participants: App\Infrastructure\Session\Persistence\Doctrine\Type\MaxParticipantsType
            num_bookings: App\Infrastructure\Session\Persistence\Doctrine\Type\NumBookingsType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/domain'
                prefix: 'App\Domain'
                alias: Domain
            Projections:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/projection'
                prefix: 'App\Infrastructure'
                alias: Projection
