parameters:
    exception_to_status:
        InvalidArgumentException: 400
        App\Domain\User\Exception\InvalidCredentialsException: 401
        App\Domain\User\Exception\ForbiddenException: 403
        App\Domain\User\Exception\EmailAlreadyExistException: 403

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $eventBus: '@broadway.event_handling.event_bus'
            $eventStore: '@Broadway\EventStore\Dbal\DBALEventStore'

    _instanceof:
        App\Application\Command\Shared\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }
    
        App\Application\Query\Shared\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }
    
        Broadway\EventHandling\EventListener:
            public: true
            tags:
                - { name: broadway.domain.event_listener }

    App\:
        resource: '../src/*'
        exclude: '../src/Infrastructure/Shared/Persistence/Doctrine/Migration/*'

    App\Infrastructure\Shared\Bus\Command\MessengerCommandBus:
        arguments:
            - '@messenger.bus.command'

    App\Infrastructure\Shared\Bus\Query\MessengerQueryBus:
        arguments:
            - '@messenger.bus.query'

    App\Infrastructure\Shared\Bus\AsyncEvent\MessengerAsyncEventBus:
        arguments:
            - '@messenger.bus.event.async'

    ### PORTS
    
    App\Ports\Http\Rest\Controller\:
        resource: '../src/Ports/Http/Rest/Controller/*'
        tags: [ 'controller.service_arguments' ]
        
    App\Ports\Cli\:
        resource: '../src/Ports/Cli'

    ### UI Listeners

    App\Ports\Http\Rest\EventSubscriber\ExceptionSubscriber:
        arguments:
            - "%kernel.environment%"
            - "%exception_to_status%"
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    ### Repositories
    
    App\Domain\User\Repository\UserRepositoryInterface: '@App\Infrastructure\User\ReadModel\Repository\UserRepository'
    App\Domain\User\Repository\UserStoreRepositoryInterface: '@App\Infrastructure\User\Repository\UserStoreRepository'
    App\Domain\Booking\Repository\BookingRepositoryInterface: '@App\Infrastructure\Booking\ReadModel\Repository\BookingRepository'
    App\Domain\Booking\Repository\BookingStoreRepositoryInterface: '@App\Infrastructure\Booking\Repository\BookingStoreRepository'
    App\Domain\Session\Repository\SessionRepositoryInterface: '@App\Infrastructure\Session\ReadModel\Repository\SessionRepository'
    App\Domain\Session\Repository\SessionStoreRepositoryInterface: '@App\Infrastructure\Session\Repository\SessionStoreRepository'

    ### Projection
    App\Infrastructure\User\ReadModel\Projection\:
        resource: '../src/Infrastructure/User/ReadModel/Projection/*'
        tags: [ 'broadway.domain.event_listener' ]
        
    App\Infrastructure\Booking\ReadModel\Projection\:
        resource: '../src/Infrastructure/Booking/ReadModel/Projection/*'
        tags: [ 'broadway.domain.event_listener' ]
